### ISSUE TITLE
running example from muscle3 training results in unexpected error

### ISSUE THREAD

**Issue by meiertgrootes** [multiscale/ymmsl-python#14]
Running the coupled_model.py example produces the following error:
```
'(cws) c-001-001-002:model_coupling eslt0101$ python3 coupled_model.py
Traceback (most recent call last):
  File "/Users/eslt0101/Projects/REPOS/eScience/couplingWS/model_coupling/coupled_model.py", line 23, in <module>
    configuration = ymmsl.load(Path('reaction_diffusion.ymmsl'))
  File "/Users/eslt0101/mambaforge/envs/cws/lib/python3.10/site-packages/ymmsl/io.py", line 41, in load
    return _load(source)
  File "/Users/eslt0101/mambaforge/envs/cws/lib/python3.10/site-packages/yatiml/loader.py", line 394, in __call__
    return cast(T, yaml.load(f, Loader=self.loader))
  File "/Users/eslt0101/mambaforge/envs/cws/lib/python3.10/site-packages/ruamel/yaml/main.py", line 951, in load
    return loader._constructor.get_single_data()
  File "/Users/eslt0101/mambaforge/envs/cws/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "/Users/eslt0101/mambaforge/envs/cws/lib/python3.10/site-packages/yatiml/loader.py", line 60, in get_single_node
    node = self.__process_node(node, type(self).document_type)
  File "/Users/eslt0101/mambaforge/envs/cws/lib/python3.10/site-packages/yatiml/loader.py", line 162, in __process_node
    node = self.__savorize(node, recognized_type)
  File "/Users/eslt0101/mambaforge/envs/cws/lib/python3.10/site-packages/yatiml/loader.py", line 127, in __savorize
    expected_type._yatiml_savorize(cnode)
  File "/Users/eslt0101/mambaforge/envs/cws/lib/python3.10/site-packages/ymmsl/configuration.py", line 155, in _yatiml_savorize
    node.map_attribute_to_index('resources', 'name')
  File "/Users/eslt0101/mambaforge/envs/cws/lib/python3.10/site-packages/yatiml/helpers.py", line 886, in map_attribute_to_index
    if isinstance(new_mapping, yaml.MappingNode):
UnboundLocalError: local variable 'new_mapping' referenced before assignment
`
```
the ymmsl file used is the following:

```
ymmsl_version: v0.1

model:
  name: reaction_diffusion

  components:
    macro:
      implementation: diffusion
      ports:
        o_i: state_out
        s: state_in
        o_f: final_state_out

    micro:
      implementation: reaction
      ports:
        f_init: initial_state
        o_f: final_state  

  conduits:
    macro.state_out: micro.initial_state
    micro.final_state: macro.state_in

settings:
  micro.t_max: 2.469136e-6
  micro.dt: 2.469136e-8
  micro.k: -4.05e4
  macro.t_max: 1.234568e-4
  macro.dt: 2.469136e-6
  x_max: 1.01
  dx: 0.01
  d: 4.05e-2


resources:
  macro:
    threads:1
  micro:
    threads:2

```

**Comment by LourensVeen** [comment]
Ah, this may be a bug in YAtiML that I fixed in April, but which fix only just got released. Should check this with YAtiML 0.10.0 to see if that's the case.

**Comment by LourensVeen** [comment]
YAtiML 0.10.0 gives a better error message, but it still does not accept the file. The problem is that there is no space after the colon for the `threads` keys in the resources section, so ruamel.yaml doesn't parse it as a mapping. Something for the next YAtiML to give a better hint on maybe.
